import { useState } from 'react';
import { ArrowRight, Menu, X, Utensils, BriefcaseBusiness, Languages, Lightbulb, Sparkles, Boxes, Workflow, ScanText } from 'lucide-react';

const solutions = [
  { icon: Utensils, title: 'Dish Manager', subtitle: 'Operación inteligente para restaurantes.', description: 'Inventario, compras y rentabilidad conectados en una sola vista para decidir mejor cada día.', href: '/dish-manager', tone: 'from-cyan-400/20 to-blue-600/10' },
  { icon: BriefcaseBusiness, title: 'Nina Manager', subtitle: 'Claridad para emprender y crecer.', description: 'Una solución cercana para organizar las áreas clave de tu negocio y convertir el caos en avance.', href: '/nina-manager', tone: 'from-fuchsia-400/20 to-violet-600/10' },
  { icon: Languages, title: 'Traductor Profesional', subtitle: 'Documentos que conservan su sentido.', description: 'Transforma PDFs e imágenes en documentos Word editables, preservando estructura y contexto.', href: '/traductor-profesional', tone: 'from-blue-400/20 to-violet-600/10' },
];

const steps = [
  ['01', 'Entender', 'Observamos el problema antes de elegir la herramienta.'],
  ['02', 'Diseñar', 'Damos forma a una solución clara, útil y posible.'],
  ['03', 'Construir', 'Convertimos la idea en una experiencia que funciona.'],
  ['04', 'Mejorar', 'Medimos, aprendemos y hacemos que evolucione.'],
];

function GlowOrb({ className = '' }: { className?: string }) { return <div aria-hidden="true" className={`pointer-events-none absolute rounded-full blur-3xl ${className}`} />; }

export default function CorporateHome() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <div className="min-h-screen overflow-hidden bg-[#050816] text-slate-100 selection:bg-cyan-300 selection:text-[#050816]">
    <header className="sticky top-0 z-50 border-b border-white/10 bg-[#050816]/75 backdrop-blur-xl">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10">
        <a href="#inicio" onClick={closeMenu} className="flex items-center gap-3 text-sm font-semibold tracking-[0.2em]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-300 via-blue-500 to-fuchsia-500 text-sm font-black text-[#050816] shadow-[0_0_25px_rgba(34,211,238,.35)]">S</span> STRELLATECH</a>
        <button className="rounded-lg p-2 text-slate-200 lg:hidden" aria-label="Abrir menú" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
        <nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 right-0 top-full flex-col gap-5 border-b border-white/10 bg-[#080c20] px-6 py-6 lg:static lg:flex lg:flex-row lg:items-center lg:border-0 lg:bg-transparent lg:p-0`}>
          {['Soluciones', 'Aprendizaje', 'Nosotros', 'Contacto'].map((item, index) => <a key={item} href={['#soluciones', '#aprendizaje', '#nosotros', '#contacto'][index]} onClick={closeMenu} className="text-sm text-slate-400 transition hover:text-cyan-300">{item}</a>)}
          <a href="#contacto" onClick={closeMenu} className="rounded-full border border-cyan-300/40 px-4 py-2 text-sm text-cyan-200 transition hover:bg-cyan-300/10">Construyamos algo</a>
        </nav>
      </div>
    </header>
    <main id="inicio">
      <section className="relative mx-auto grid max-w-7xl gap-16 px-6 pb-24 pt-24 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-32">
        <GlowOrb className="-left-40 -top-40 h-96 w-96 bg-blue-600/20" /><GlowOrb className="right-0 top-20 h-80 w-80 bg-fuchsia-500/15" />
        <div className="relative"><p className="mb-7 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.25em] text-cyan-300"><span className="h-px w-8 bg-cyan-300" /> Tecnología con propósito</p><h1 className="max-w-3xl text-5xl font-semibold leading-[.98] tracking-[-0.06em] sm:text-7xl lg:text-8xl">Tecnología aplicada a <span className="bg-gradient-to-r from-cyan-300 via-blue-400 to-fuchsia-400 bg-clip-text text-transparent">problemas reales.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-slate-400">Construimos soluciones digitales para empresas y experiencias de aprendizaje para quienes quieren convertir una idea en algo que funciona.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#soluciones" className="rounded-full bg-gradient-to-r from-cyan-300 to-blue-500 px-6 py-3.5 text-sm font-bold text-[#050816] shadow-[0_0_30px_rgba(34,211,238,.2)] transition hover:shadow-[0_0_40px_rgba(34,211,238,.4)]">Explorar soluciones <ArrowRight className="ml-2 inline h-4 w-4" /></a><a href="#aprendizaje" className="rounded-full border border-white/15 px-6 py-3.5 text-sm font-semibold text-slate-200 transition hover:border-fuchsia-300/50 hover:bg-white/5">Conocer el Bootcamp</a></div></div>
        <div className="relative min-h-[420px] overflow-hidden rounded-[2rem] border border-white/10 bg-white/[0.04] p-8 shadow-2xl backdrop-blur-sm sm:p-10"><GlowOrb className="-right-20 -top-20 h-64 w-64 bg-cyan-400/25" /><GlowOrb className="-bottom-24 -left-16 h-72 w-72 bg-fuchsia-500/20" /><div className="relative flex h-full flex-col justify-between"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[0.2em] text-slate-400"><span>Idea → sistema → solución</span><Sparkles className="h-4 w-4 text-cyan-300" /></div><div className="relative mx-auto flex h-64 w-full max-w-sm items-center justify-center"><div className="absolute h-52 w-52 rounded-full border border-cyan-300/20 shadow-[0_0_80px_rgba(34,211,238,.15)]" /><div className="absolute h-32 w-32 rounded-full border border-fuchsia-300/25" /><div className="absolute h-20 w-20 rounded-full bg-gradient-to-br from-cyan-300 via-blue-500 to-fuchsia-500 shadow-[0_0_55px_rgba(96,165,250,.7)]" /><div className="absolute left-5 top-12 h-3 w-3 rounded-full bg-cyan-300 shadow-[0_0_18px_cyan]" /><div className="absolute right-10 top-24 h-2 w-2 rounded-full bg-fuchsia-300 shadow-[0_0_18px_fuchsia]" /><div className="absolute bottom-10 left-20 h-2 w-2 rounded-full bg-blue-300 shadow-[0_0_18px_#60a5fa]" /></div><p className="relative max-w-xs text-2xl font-medium leading-tight tracking-[-0.04em] text-white">Las ideas brillan cuando se convierten en movimiento.</p></div></div>
      </section>
      <section className="relative border-y border-white/10 bg-[#080d21]" id="que-hacemos"><GlowOrb className="right-0 top-1/2 h-80 w-80 bg-blue-600/10" /><div className="relative mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-300">¿Qué hacemos?</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-[-0.05em] sm:text-6xl">Diseñamos lo que todavía no existe.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-400">Combinamos estrategia, diseño, tecnología e inteligencia artificial para resolver problemas concretos y crear nuevas posibilidades.</p><div className="mt-14 grid gap-5 md:grid-cols-2"><div className="rounded-3xl border border-cyan-300/20 bg-gradient-to-br from-cyan-300/10 to-blue-600/5 p-8"><Boxes className="h-8 w-8 text-cyan-300" /><p className="mt-12 text-2xl font-medium">Soluciones empresariales</p><p className="mt-3 leading-7 text-slate-400">Herramientas digitales diseñadas alrededor de la operación real de cada negocio.</p></div><div className="rounded-3xl border border-fuchsia-300/20 bg-gradient-to-br from-fuchsia-300/10 to-violet-600/5 p-8"><Lightbulb className="h-8 w-8 text-fuchsia-300" /><p className="mt-12 text-2xl font-medium">Aprendizaje</p><p className="mt-3 leading-7 text-slate-400">Experiencias prácticas para construir aplicaciones con inteligencia artificial.</p></div></div></div></section>
      <section id="soluciones" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-300">Soluciones empresariales</p><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="mt-5 max-w-3xl text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Tecnología que entiende tu contexto.</h2><p className="max-w-xs text-sm leading-6 text-slate-500">Tres caminos. Una misma convicción: hacer el trabajo más claro.</p></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{solutions.map(({ icon: Icon, ...solution }) => <article key={solution.title} className={`group relative flex flex-col overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br ${solution.tone} p-7 transition hover:-translate-y-1 hover:border-cyan-300/30`}><div className="absolute -right-16 -top-16 h-40 w-40 rounded-full bg-white/5 blur-2xl" /><div className="relative mb-16 flex h-12 w-12 items-center justify-center rounded-2xl border border-white/15 bg-white/10 text-cyan-200"><Icon /></div><h3 className="relative text-2xl font-semibold">{solution.title}</h3><p className="relative mt-2 font-medium text-cyan-200">{solution.subtitle}</p><p className="relative mt-5 flex-1 leading-7 text-slate-400">{solution.description}</p><a href={solution.href} className="relative mt-8 text-sm font-bold text-white transition group-hover:text-cyan-300">Conocer {solution.title} <ArrowRight className="ml-1 inline h-4 w-4" /></a></article>)}</div></section>
      <section className="relative overflow-hidden bg-gradient-to-r from-blue-700 via-violet-700 to-fuchsia-700 px-6 py-24 text-center"><div className="absolute inset-0 bg-[#050816]/25" /><div className="relative"><p className="mx-auto max-w-4xl text-4xl font-semibold leading-tight tracking-[-0.05em] sm:text-6xl">Cada problema abre una puerta.<br /><span className="text-cyan-200">Nosotros ayudamos a cruzarla.</span></p></div></section>
      <section id="aprendizaje" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-fuchsia-300">Aprendizaje</p><h2 className="mt-5 text-4xl font-semibold leading-tight tracking-[-0.05em] sm:text-6xl">Aprende a construir tu propia solución.</h2></div><div className="relative overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] p-8 sm:p-10"><GlowOrb className="-right-20 -top-24 h-64 w-64 bg-fuchsia-500/15" /><div className="relative"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-fuchsia-400 to-violet-600 text-white"><Lightbulb /></div><h3 className="mt-8 text-3xl font-semibold">Tu primera aplicación empresarial con IA</h3><p className="mt-4 max-w-2xl leading-7 text-slate-400">Un bootcamp práctico para transformar un problema real de negocio en una aplicación funcional.</p><div className="my-10 flex flex-wrap items-center gap-3 text-sm font-semibold">{['Idea', 'Diseño', 'Construcción', 'Aplicación'].map((step, i) => <span key={step} className="flex items-center gap-3"><span className="rounded-full border border-fuchsia-300/30 px-3 py-2 text-fuchsia-200">0{i + 1} {step}</span>{i < 3 && <ArrowRight className="h-4 w-4 text-slate-600" />}</span>)}</div><a href="/bootcamp" className="inline-flex items-center rounded-full bg-white px-6 py-3.5 text-sm font-bold text-[#090d20]">Conocer el Bootcamp <ArrowRight className="ml-2 h-4 w-4" /></a></div></div></div></section>
      <section id="nosotros" className="border-y border-white/10 bg-[#080d21] px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-300">Nuestra forma de crear</p><h2 className="mt-5 max-w-3xl text-4xl font-semibold leading-tight tracking-[-0.05em] sm:text-6xl">No empezamos con la tecnología.<br /><span className="text-slate-400">Empezamos con el problema.</span></h2><div className="relative mt-16 grid gap-10 sm:grid-cols-2 lg:grid-cols-4">{steps.map(([num, title, text], i) => <div key={num} className="relative"><div className="mb-6 flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full border border-cyan-300/40 text-xs font-bold text-cyan-200">{num}</span>{i < 3 && <span className="hidden h-px flex-1 bg-gradient-to-r from-cyan-300/50 to-fuchsia-300/20 lg:block" />}</div><h3 className="text-xl font-semibold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></div>)}</div></div></section>
      <section id="contacto" className="relative px-6 py-24 lg:px-10"><GlowOrb className="left-1/3 top-1/3 h-96 w-96 bg-cyan-500/10" /><div className="relative mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-end"><h2 className="max-w-xl text-5xl font-semibold tracking-[-0.06em] sm:text-7xl">¿Qué quieres construir?</h2><div className="grid gap-4 sm:grid-cols-2"><a href="#soluciones" className="rounded-3xl border border-white/10 bg-white/[0.04] p-6 transition hover:border-cyan-300/40"><ScanText className="h-6 w-6 text-cyan-300" /><p className="mt-8 font-semibold">Una solución para tu negocio</p><p className="mt-2 text-sm leading-6 text-slate-400">Explora nuestras herramientas empresariales.</p></a><a href="/bootcamp" className="rounded-3xl border border-fuchsia-300/20 bg-gradient-to-br from-fuchsia-500/15 to-violet-500/10 p-6 transition hover:border-fuchsia-300/50"><Workflow className="h-6 w-6 text-fuchsia-300" /><p className="mt-8 font-semibold">Tu primera aplicación</p><p className="mt-2 text-sm leading-6 text-slate-400">Aprende a construirla paso a paso.</p></a></div></div></section>
    </main>
    <footer className="border-t border-white/10 bg-[#030510] px-6 py-14 text-slate-400 lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 sm:grid-cols-2 lg:grid-cols-4"><div><p className="font-semibold tracking-[0.2em] text-white">STRELLATECH</p><p className="mt-4 max-w-xs text-xs tracking-[0.18em]">TECNOLOGÍA APLICADA A PROBLEMAS REALES.</p></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-cyan-300">Soluciones</p><div className="mt-5 grid gap-3 text-sm"><a href="/dish-manager">Dish Manager</a><a href="/nina-manager">Nina Manager</a><a href="/traductor-profesional">Traductor Profesional</a></div></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-fuchsia-300">Aprendizaje</p><a href="/bootcamp" className="mt-5 block text-sm">Tu primera aplicación empresarial con IA</a></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-300">Empresa</p><div className="mt-5 grid gap-3 text-sm"><a href="/nosotros">Nosotros</a><a href="mailto:hola@strellatech.com">Contacto</a></div></div></div><div className="mx-auto mt-14 max-w-7xl border-t border-white/10 pt-6 text-xs">© 2026 StrellaTech</div></footer>
  </div>;
}

export function FuturePage({ title }: { title: string }) { return <div className="grid min-h-screen place-items-center bg-[#050816] px-6 text-center text-white"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-cyan-300">StrellaTech</p><h1 className="mt-5 text-5xl font-semibold tracking-[-0.05em]">{title}</h1><p className="mt-4 text-slate-400">Próximamente.</p><a href="/" className="mt-8 inline-block rounded-full bg-gradient-to-r from-cyan-300 to-blue-500 px-6 py-3 text-sm font-bold text-[#050816]">Volver a StrellaTech</a></div></div>; }

export function AppRouter({ DishManagerApp }: { DishManagerApp: React.ComponentType }) { const path = window.location.pathname; if (path === '/dish-manager') return <DishManagerApp />; if (path === '/nina-manager') return <FuturePage title="Nina Manager" />; if (path === '/traductor-profesional') return <FuturePage title="Traductor Profesional" />; if (path === '/bootcamp') return <FuturePage title="Tu primera aplicación empresarial con IA" />; if (path === '/nosotros') return <FuturePage title="Nosotros" />; return <CorporateHome />; }

export { solutions };
