import { useState } from 'react';
import { ArrowRight, Menu, X, Utensils, BriefcaseBusiness, Languages, Lightbulb, Check } from 'lucide-react';

const solutions = [
  { icon: Utensils, title: 'Dish Manager', subtitle: 'Gestión inteligente para restaurantes.', description: 'Una plataforma para gestionar las operaciones de un restaurante desde un mismo lugar: inventario, compras, pagos, personal, mermas y rentabilidad.', href: '/dish-manager', featured: true },
  { icon: BriefcaseBusiness, title: 'Nina Manager', subtitle: 'Gestión para emprendedoras.', description: 'Una solución pensada para ayudar a emprendedoras a organizar y controlar las áreas clave de su negocio.', href: '/nina-manager' },
  { icon: Languages, title: 'Traductor Profesional', subtitle: 'Del documento original al Word traducido.', description: 'Procesa PDFs, imágenes y documentos escaneados, traduce su contenido y reconstruye su estructura en un documento Word editable.', href: '/traductor-profesional' },
];

export default function CorporateHome() {
  const [menuOpen, setMenuOpen] = useState(false);
  const closeMenu = () => setMenuOpen(false);
  return <div className="min-h-screen bg-[#f7f8f5] text-[#14231d] selection:bg-[#b9d8c6] selection:text-[#14231d]">
    <header className="sticky top-0 z-50 border-b border-[#dce5df] bg-[#f7f8f5]/95 backdrop-blur">
      <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5 lg:px-10">
        <a href="#inicio" className="flex items-center gap-3 text-sm font-semibold tracking-[0.18em]" onClick={closeMenu}><span className="grid h-9 w-9 place-items-center rounded-full bg-[#173d31] text-[#d8ecd8]">S</span> STRELLATECH</a>
        <button className="rounded-lg p-2 lg:hidden" aria-label="Abrir menú" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
        <nav className={`${menuOpen ? 'flex' : 'hidden'} absolute left-0 right-0 top-full flex-col gap-5 border-b border-[#dce5df] bg-[#f7f8f5] px-6 py-6 lg:static lg:flex lg:flex-row lg:items-center lg:border-0 lg:bg-transparent lg:p-0`}>
          <a href="#soluciones" onClick={closeMenu} className="text-sm text-[#53665d] hover:text-[#173d31]">Soluciones</a><a href="#aprendizaje" onClick={closeMenu} className="text-sm text-[#53665d] hover:text-[#173d31]">Aprendizaje</a><a href="#nosotros" onClick={closeMenu} className="text-sm text-[#53665d] hover:text-[#173d31]">Nosotros</a><a href="#contacto" onClick={closeMenu} className="text-sm text-[#53665d] hover:text-[#173d31]">Contacto</a>
        </nav>
      </div>
    </header>
    <main id="inicio">
      <section className="mx-auto grid max-w-7xl gap-16 px-6 pb-24 pt-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-10 lg:pb-32 lg:pt-32">
        <div><p className="mb-6 text-xs font-bold uppercase tracking-[0.25em] text-[#668875]">StrellaTech · tecnología con propósito</p><h1 className="max-w-3xl text-5xl font-medium leading-[1.03] tracking-[-0.05em] sm:text-7xl">Tecnología aplicada a <span className="text-[#568269]">problemas reales.</span></h1><p className="mt-8 max-w-xl text-lg leading-8 text-[#53665d]">Creemos soluciones digitales para empresas y profesionales, y desarrollamos experiencias de aprendizaje para quienes quieren construir sus propias herramientas.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#soluciones" className="rounded-full bg-[#173d31] px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-[#285a47]">Explorar soluciones <ArrowRight className="ml-2 inline-block h-4 w-4" /></a><a href="#aprendizaje" className="rounded-full border border-[#afc5b7] px-6 py-3.5 text-sm font-semibold text-[#173d31] hover:bg-white">Conocer el Bootcamp</a></div></div>
        <div className="relative min-h-[360px] overflow-hidden rounded-[2rem] bg-[#d8e8dc] p-8"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full border-[30px] border-[#a6cbb1]" /><div className="absolute -bottom-20 -left-10 h-64 w-64 rounded-full bg-[#eff5ec]" /><div className="relative flex h-full flex-col justify-between"><span className="text-xs font-bold uppercase tracking-[0.2em] text-[#568269]">Ideas that move forward</span><div><p className="max-w-sm text-3xl leading-tight tracking-[-0.04em] text-[#173d31]">Entender. Diseñar. Construir. Mejorar.</p><div className="mt-8 flex gap-2">{['01','02','03','04'].map((n) => <span key={n} className="grid h-10 w-10 place-items-center rounded-full border border-[#9abda5] text-xs font-semibold text-[#568269]">{n}</span>)}</div></div></div></div>
      </section>
      <section className="border-y border-[#dce5df] bg-white" id="que-hacemos"><div className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#668875]">¿Qué hacemos?</p><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">Soluciones que nacen de necesidades reales.</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-[#53665d]">En StrellaTech desarrollamos herramientas digitales para resolver problemas concretos de gestión, operación y productividad. También compartimos el conocimiento para transformar ideas en aplicaciones.</p><div className="mt-14 grid gap-5 md:grid-cols-2"><div className="rounded-2xl bg-[#f0f5f0] p-8"><p className="text-xs font-bold tracking-[0.18em] text-[#568269]">SOLUCIONES EMPRESARIALES</p><p className="mt-4 text-xl">Herramientas digitales diseñadas para necesidades específicas de negocio.</p></div><div className="rounded-2xl bg-[#173d31] p-8 text-white"><p className="text-xs font-bold tracking-[0.18em] text-[#b9d8c6]">APRENDIZAJE</p><p className="mt-4 text-xl">Experiencias prácticas para crear aplicaciones empresariales con inteligencia artificial.</p></div></div></div></section>
      <section id="soluciones" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#668875]">Soluciones empresariales</p><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><h2 className="mt-5 text-4xl font-medium tracking-[-0.04em] sm:text-5xl">Herramientas para hacer más sencillo el trabajo.</h2></div><div className="mt-14 grid gap-5 lg:grid-cols-3">{solutions.map(({ icon: Icon, ...solution }) => <article key={solution.title} className={`flex flex-col rounded-2xl border p-7 ${solution.featured ? 'border-[#9fc1aa] bg-white shadow-[0_14px_40px_rgba(23,61,49,.08)]' : 'border-[#dce5df] bg-transparent'}`}><div className="mb-14 flex h-12 w-12 items-center justify-center rounded-xl bg-[#e1eee3] text-[#32654c]"><Icon /></div><h3 className="text-2xl font-medium">{solution.title}</h3><p className="mt-2 font-medium text-[#568269]">{solution.subtitle}</p><p className="mt-5 flex-1 leading-7 text-[#53665d]">{solution.description}</p><a href={solution.href} className="mt-8 text-sm font-semibold text-[#173d31] hover:text-[#568269]">Conocer {solution.title} <ArrowRight className="ml-1 inline h-4 w-4" /></a></article>)}</div></section>
      <section className="bg-[#173d31] px-6 py-20 text-center text-white"><p className="mx-auto max-w-3xl text-3xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">Cada negocio tiene problemas diferentes.<br /><span className="text-[#b9d8c6]">Las soluciones también deberían serlo.</span></p></section>
      <section id="aprendizaje" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#668875]">Aprendizaje</p><h2 className="mt-5 text-4xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">Aprende a construir tu propia solución.</h2></div><div className="rounded-2xl border border-[#cbdcd0] bg-white p-8 sm:p-10"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#e1eee3] text-[#32654c]"><Lightbulb /></div><h3 className="mt-8 text-3xl font-medium">Tu primera aplicación empresarial con IA</h3><p className="mt-4 max-w-2xl leading-7 text-[#53665d]">Un bootcamp práctico para transformar un problema real de negocio en una aplicación funcional utilizando herramientas de inteligencia artificial.</p><div className="my-8 grid grid-cols-2 gap-4 text-sm font-semibold sm:grid-cols-4">{['Pensar','Diseñar','Construir','Probar'].map((step, i) => <div key={step} className="border-l-2 border-[#9fc1aa] pl-3"><span className="block text-xs text-[#8ba395]">0{i + 1}</span>{step}</div>)}</div><a href="/bootcamp" className="inline-flex items-center rounded-full bg-[#173d31] px-6 py-3.5 text-sm font-semibold text-white">Conocer el Bootcamp <ArrowRight className="ml-2 h-4 w-4" /></a></div></div></section>
      <section className="border-y border-[#dce5df] bg-white px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#668875]">Nuestra forma de crear</p><h2 className="mt-5 max-w-2xl text-4xl font-medium leading-tight tracking-[-0.04em] sm:text-5xl">No empezamos con la tecnología.<br />Empezamos con el problema.</h2><div className="mt-14 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[['01','Entender','Identificamos qué necesita realmente el usuario.'],['02','Diseñar','Convertimos esa necesidad en una solución clara.'],['03','Construir','Creamos herramientas digitales funcionales.'],['04','Mejorar','Probamos, aprendemos y evolucionamos la solución.']].map(([num, title, text]) => <div key={num}><span className="text-sm font-bold text-[#8ba395]">{num}</span><h3 className="mt-5 text-xl font-medium">{title}</h3><p className="mt-3 leading-7 text-[#53665d]">{text}</p></div>)}</div></div></section>
      <section id="nosotros" className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#668875]">Sobre StrellaTech</p><h2 className="mt-5 text-4xl font-medium tracking-[-0.04em] sm:text-5xl">Tecnología con propósito.</h2><p className="mt-7 text-xl leading-9 text-[#53665d]">StrellaTech nace de una idea sencilla: la tecnología tiene más valor cuando resuelve un problema real. Creamos productos digitales y experiencias de aprendizaje combinando tecnología, diseño y nuevas herramientas de inteligencia artificial.</p><a href="/nosotros" className="mt-8 inline-flex items-center text-sm font-semibold text-[#173d31]">Conocer StrellaTech <ArrowRight className="ml-2 h-4 w-4" /></a></div></section>
      <section id="contacto" className="bg-[#d8e8dc] px-6 py-20"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-2 lg:items-end"><h2 className="text-4xl font-medium tracking-[-0.04em] sm:text-6xl">¿Qué quieres construir?</h2><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-6"><p className="font-semibold">Una solución para tu negocio</p><p className="mt-2 text-sm leading-6 text-[#53665d]">Explora nuestras soluciones empresariales.</p><a href="#soluciones" className="mt-5 inline-flex text-sm font-semibold">Explorar soluciones <ArrowRight className="ml-1 h-4 w-4" /></a></div><div className="rounded-2xl bg-[#173d31] p-6 text-white"><p className="font-semibold">Tu primera aplicación</p><p className="mt-2 text-sm leading-6 text-[#d8ecd8]">Aprende a construirla paso a paso.</p><a href="/bootcamp" className="mt-5 inline-flex text-sm font-semibold text-[#b9d8c6]">Conocer el Bootcamp <ArrowRight className="ml-1 h-4 w-4" /></a></div></div></div></section>
    </main>
    <footer className="bg-[#102a22] px-6 py-14 text-[#d8ecd8] lg:px-10"><div className="mx-auto grid max-w-7xl gap-12 sm:grid-cols-2 lg:grid-cols-4"><div><p className="font-semibold tracking-[0.18em]">STRELLATECH</p><p className="mt-4 max-w-xs text-xs tracking-[0.18em] text-[#9bb9a5]">TECNOLOGÍA APLICADA A PROBLEMAS REALES.</p></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#9bb9a5]">Soluciones</p><div className="mt-5 grid gap-3 text-sm"><a href="/dish-manager">Dish Manager</a><a href="/nina-manager">Nina Manager</a><a href="/traductor-profesional">Traductor Profesional</a></div></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#9bb9a5]">Aprendizaje</p><a href="/bootcamp" className="mt-5 block text-sm">Tu primera aplicación empresarial con IA</a></div><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#9bb9a5]">Empresa</p><div className="mt-5 grid gap-3 text-sm"><a href="/nosotros">Nosotros</a><a href="mailto:hola@strellatech.com">Contacto</a></div></div></div><div className="mx-auto mt-14 max-w-7xl border-t border-[#315242] pt-6 text-xs text-[#9bb9a5]">© 2026 StrellaTech</div></footer>
  </div>;
}

export function FuturePage({ title }: { title: string }) { return <div className="grid min-h-screen place-items-center bg-[#f7f8f5] px-6 text-center"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-[#668875]">StrellaTech</p><h1 className="mt-5 text-5xl font-medium tracking-[-0.04em]">{title}</h1><p className="mt-4 text-[#53665d]">Próximamente.</p><a href="/" className="mt-8 inline-block rounded-full bg-[#173d31] px-6 py-3 text-sm font-semibold text-white">Volver a StrellaTech</a></div></div>; }

export function AppRouter({ DishManagerApp }: { DishManagerApp: React.ComponentType }) { const path = window.location.pathname; if (path === '/dish-manager') return <DishManagerApp />; if (path === '/nina-manager') return <FuturePage title="Nina Manager" />; if (path === '/traductor-profesional') return <FuturePage title="Traductor Profesional" />; if (path === '/bootcamp') return <FuturePage title="Tu primera aplicación empresarial con IA" />; if (path === '/nosotros') return <FuturePage title="Nosotros" />; return <CorporateHome />; }

import React from 'react';
  
